# Site settings
title: The ESPI Developer Blog
email: d.steinel@de.edenspiekermann.com
description: Rumblings from the devs at Edenspiekermann. Front-end, back-end, deep-end.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dev.edenspiekermann.com" # the base hostname & protocol for your site
twitter_username: edenspiekermann
github_username:  edenspiekermann
logo_image: /assets/images/espi-dev-blog-logo.png

sass:
  sass_dir: assets/sass
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty
